### ISSUE TITLE
Pull request merge does not trigger

### ISSUE THREAD

**Issue by dlubitz** [TrimbleSolutionsCorporation/TeamcityTriggerHook#17]
If I merge a pull request of a feature into a target branch via bitbucket, this does not tigger a team city build. It needs a follow up commit in any branch, to trigger team city.

Would be good if the the plugin could also trigger team city in case of a merge into the target branch.

Thanks
Denny

**Comment by jmecosta** [comment]
You need to configure a rule to the target branch.  we are using this and
works properly.

Maybe you can describe more the layout of branches and your configuration

**Comment by dlubitz** [comment]
I do. I have multiple feature branches and on development branch. I like just to build after I've merged a PR into the development or if I commit into the development directly.

As branch filter I've configured:
```+:development
+:refs/heads/development```

This works fine with direct commits but not with merged PRs.

**Comment by jmecosta** [comment]
But I need to know your configuration from bitbucket side. Are you using
vcs root trigger or build configuration trigger. Tell me the rules you have
defined in bitbucket also. You can share screenshot

It's hard to investigate this if you don't tell me the branch layout you
are using

As I said, merge commits should trigger build configurations

**Comment by dlubitz** [comment]
Connection:
* Bitbucket URL: https://bitbucket.<myserver>.com
* Trigger Type: vcs
* Teamcity URL: https://teamcity.<myserver>.com
* User Name: <username>

Build Configurations:
* master: vcsRoot
* feature: vcsRoot
* Custom Branch: development => vcsRoot

**Comment by jmecosta** [comment]
Exactly you are using vcs type, what that does is tell teamcity to check
for changes. So after that teamcity handles all the build or not

If not mistaken this is a problem in teamcity side, because you have
feature builds and target branch in same configuration then teamcity does
not build since it considered there are no changes.

I recommend you to use the other trigger setting and set the builds to
trigger, that should do what you need plus it's instant

**Comment by dlubitz** [comment]
Ok, thanks. I'll check this. 
> So after that teamcity handles all the build or not
That works also after a new commit after the merge. Just the merge itself is not triggering the build.

**Comment by jmecosta** [comment]
it works, because the check ofr changes detect new changes. we dont have any logic in the bitbucket side to filter merge commits. you should see in the bitbucket log that after each merge and check for changes command is sent by the hook. what teamctiy does after that i cannot control

**Comment by dlubitz** [comment]
Ok, thanks
