### ISSUE TITLE
Error: At least on configuration should be set

### ISSUE THREAD

**Issue by MikeF74** [TrimbleSolutionsCorporation/TeamcityTriggerHook#19]
"At least o configuration should be set".  

Issue 1: I assume that is a typo and "on" should be "one".

I don't know what this is trying to tell me.  I'm using v3.1, which brings up another issue.  There is a serious mismatch between versioning on this GitHub and the versioning listed here:
https://marketplace.atlassian.com/plugins/com.trimble.tekla/versions

One last minor typo that doesn't really merit its own issue...  "Teamcity" should be "TeamCity" throughout the project to match JetBrains' branding.

**Comment by jmecosta** [comment]
@MikeF74 thanks. i will  fix those typos in next version. Indeed releasing in both places becomes a bit difficult to manage. so we will be dropping the releases here in favour of marketplace.

the message is telling you need to define at least one of the follwing configurations: master, feature or bugfix

**Comment by jmecosta** [comment]
@MikeF74 please update to latest
