### ISSUE TITLE
TeamCity passwords with special characters fail

### ISSUE THREAD

**Issue by MikeF74** [TrimbleSolutionsCorporation/TeamcityTriggerHook#20]
When trying to use a TeamCity password that ends in "!@#" (exclamation point, at-symbol, number symbol), the password would never be accepted by the "Test and Save Connection" button.  I'm not sure which character it fails on, but one of those characters causes a login failure.

**Comment by jmecosta** [comment]
nice, thanks for reporting. i will espace the password before sending to server.

**Comment by jmecosta** [comment]
@MikeF74 please check with latest version in marketplace
