### ISSUE TITLE
Custom branch regex doesn't work

### ISSUE THREAD

**Issue by Silwest** [TrimbleSolutionsCorporation/TeamcityTriggerHook#26]
Hello guys,

From what can I see custom branch regex in config of the plugin doesn't work. I tried different regex and end up with:
`.*refactor.*`
So each branch which have `refactor` in it should be triggered in TC. Unfortunately this is not the case ...

I took a peek on the code and per my understanding in `TeamCityTriggerHook` the regex is correctly processed ... 

Could you please take a look.

**Comment by jmecosta** [comment]
hi,

can you enable debug mode, and see if its being triggered in the server logs?

**Comment by Silwest** [comment]
It's not ;/

**Comment by jmecosta** [comment]
@Silwest beeing worked on #29

**Comment by jmecosta** [comment]
@Silwest please verify with 4.0.1
