### ISSUE TITLE
Try to fire the hook for refs/pull-requests/.*/merge

### ISSUE THREAD

**Issue by dzwicker** [TrimbleSolutionsCorporation/TeamcityTriggerHook#56]
Bitbucket creates a commit for every PR where the PR is already merged. The ref for this commit is `refs/pull-requests/<pr-number>/merge`. I have created a rule
```
"4bba60c1-710a-449e-8481-1704fb4aa0d5": {
        "regex": "refs/(pull-requests/.*)/merge",
        "target": "eservice_backend_EServiceV3prTest_GradleBuildUnitTest",
        "type": "build",
        "triggerOnEmptyBranches": true,
        "triggerOnPullRequest": false,
        "cancelRunningBuilds": false,
        "triggerInclusion": "",
        "triggerExclusion": "",
        "downStreamTriggerType": "build",
        "downStreamTriggerDescription": "",
        "downStreamTriggerTarget": ""
    }
```
But this seams not to work.

**Comment by jmecosta** [comment]
Are the branch definitions set in tenacity?

**Comment by dzwicker** [comment]
yes, branch defs in TC are set. In TC i can trigger the branch manually.

Can this be a problem of this special branch. It is only managed by bitbucket. The user pushes its feature branch and creates a PR and bitbucket create/updates the `refs/pull-requests/<pr-number>/merge`.

So the listeners of the plugin are not notified?

**Comment by jmecosta** [comment]
are u able to make it work with any other type of branch? the hook contains
some logging (Trigger From Ref:, postReceive: etc), if you enable the debug
switch you might be able to confirm that the listener is triggered, if not
then bitbucket does not support this kind of branch.

we usually just have a rule to the target branch

**Comment by dzwicker** [comment]
Ok. bitbucket doesn't trigger the plugin for this kind of branches
