### ISSUE TITLE
aui tabs broken in 6.0

### ISSUE THREAD

**Issue by jmecosta** [TrimbleSolutionsCorporation/TeamcityTriggerHook#59]
@auriusbendikas seems we have aui tabs broken in 6.0, would you have time to look at it?

**Comment by auriusbendikas** [comment]
Hi,

My current client is not using neither Bitbucket nor TeamCity. However yesterday, I have tried to boot up my old development environment. Just to see what is failing and how much work it would be to fix it. Took me almost entire Saturday afternoon to get it running to a point where I can start BitBucket 5 server. So today after compiling version of GIT that works with BitBucket 6, I discovered that master branch of plugin gets instantly disabled with exceptions and tons of deprecation warnings.

Noticed that you created "feature/6.0". So I checked it out and tried to build it, but got dependency error while trying to "atlas-package" or "atlas-run" the plugin:

```
[ERROR] Failed to execute goal com.atlassian.maven.plugins:bitbucket-maven-plugin:8.0.0:generate-rest-docs (default-generate-rest-docs) on project TeamCityTriggerHook: An error has occurred in Javadoc report generation: Unable to resolve artifact:groupId = 'com.atlassian.plugins.rest'
[ERROR] artifactId = 'atlassian-rest-doclet'
[ERROR] version = '2.9.2': Could not find artifact com.atlassian.plugins.rest:atlassian-rest-doclet:jar:2.9.2 in central (https://repo.maven.apache.org/maven2)
```

Any ideas what I have missed?

Unfortunately that was all the time I have for now. I might have time to look at it again during Easter, but can not promise :( Also would like to finish migrating my development environments (and my laptop) from Ubuntu Xenial to Archlinux, that in theory would require less maintenance than all the PAA hell of Ubuntu.

**Comment by jmecosta** [comment]
@auriusbendikas thanks for checking! The deprecated stuff is now all update. Sorry forgot to mention the feature/6.0 in my box it all compiles and runs! The only problem is the aui:tabs that is broken. 

Can the resolve artifacts be a problem of using a old sdk? Or network problem.  Im running in windows tough

**Comment by auriusbendikas** [comment]
If I remember correctly it was SDK version 8.0.4 or 8.0.7. I am pretty sure I have updated to latest version available. And it should not be network since I could build master branch without any problems, and all dependency downloads were successful. Have not tried deleting m2 folder and re-downloading everything. Will try it next time.

**Comment by jmecosta** [comment]
Then its really weird! Not much i can do this week either.  Will be on
holidyas, i will come back to this next tuesday. Thanks anyway

**Comment by Alucard1766** [comment]
Is there a way to compile the plugin myself as we are interested in a 6.x compatible version?
