### ISSUE TITLE
Demand Builds

### ISSUE THREAD

**Issue by phehr2** [TrimbleSolutionsCorporation/TeamcityTriggerHook#6]
I've switched some of our builds from Jenkins over to TeamCity and have found that TeamcityTriggerHook is a suitable replacement for the [Jenkins hook](https://marketplace.atlassian.com/plugins/com.nerdwin15.stash-stash-webhook-jenkins/overview) that we use.  The Jenkins hook has a convenient "Trigger Build" menu option available on pull requests, allowing builds to be triggered on demand when necessary.  Requesting that similar functionality be added to the TeamcityTriggerHook.

**Comment by jmecosta** [comment]
@phehr2 thanks for the reference, https://github.com/Nerdwin15/stash-jenkins-postreceive-webhook

we had also internal request for this, try to see if can be done soon

**Comment by jmecosta** [comment]
@phehr2 ive have now i implementation for remote trigger. would this be something you could try in your context?

**Comment by jmecosta** [comment]
@phehr2 please reopen if still a issue RC1 https://github.com/TrimbleSolutionsCorporation/TeamcityTriggerHook/releases/download/3.0.0-RC1/TeamcityTriggerHook-3.0.0-RC1.jar
