### ISSUE TITLE
Java 1.8.0_102-b14 is not supported in versions app version 4.5.1 or 4.5.2

### ISSUE THREAD

**Issue by GrayPockets** [TrimbleSolutionsCorporation/TeamcityTriggerHook#61]
According to [Bitbucket Supported Platforms](https://confluence.atlassian.com/bitbucketserver/supported-platforms-776640981.html), all Java versions 1.8u65+ are supported in Bitbucket.

We had Java version 1.8u102, and app version 4.5.0, and it worked just fine. However, after updating the app to 4.5.1 or 4.5.2, the app would not enable. Once we upgraded Java to 1.8u191 or 1.8u212, the app enabled just fine.

This suggests that in version 4.5.1, a higher Java version dependency was added to the app.
This dependency does not appear in the Readme.

Either fix the dependency to allow lower versions, or mention the higher java dependency in the readme.

**Steps to Reproduce**
1. Install the latest version of Bitbucket using Java 1.8u102
2. Install the TeamcityTriggerHook
3. The TeamCityTriggerHook app will not enable
4. Upgrade Java to version 1.8u191
5. The TeamCityTriggerHook app will enable

**Comment by jmecosta** [comment]
hi,

do you have any logging of the failures. i very much doubt 102 to 191 they would break backwards compatibility! Can it be a bug in the java? Usually vendors will suggest you to upgrade java and thats it.

**Comment by GrayPockets** [comment]
We turned on all logging when we did it, and were unable to see any messages. It just refused to enable with no additional messaging or logs.
Something changed in 4.5.1 that broke backwards compatibility with older versions of Java.
