### ISSUE TITLE
Must have exactly one capturing group.

### ISSUE THREAD

**Issue by damianszczepanik** [TrimbleSolutionsCorporation/TeamcityTriggerHook#64]
I have created TC configuration with
Build configuration ID = Microservices_BitBucket

then BB hook connection:
![config](https://user-images.githubusercontent.com/9612911/66651905-8d06d300-ec34-11e9-857c-2cd7ecd269ca.png)

and when trying to configure to work with `webhook` branch which is present in my repo:
![screenshot](https://user-images.githubusercontent.com/9612911/66651684-f33f2600-ec33-11e9-9f1f-e97100225f74.png)

I get error on save:
_Must have exactly one capturing group._

I haven't found `[TeamCityTriggerHook]` in attlasian-bitbucket.log file so tell me what I'm doing wrong?

**Comment by jmecosta** [comment]
+:refs/heads/feature/(*)

**Comment by jmecosta** [comment]
Note the capturing group ()

**Comment by damianszczepanik** [comment]
Then how to trigger all builds that reflect to same repo and branch? And how to avoid updating BB configuration when new TC project to same repo is created?

**Comment by jmecosta** [comment]
We typically have one entry per builconf/branch.

The vcs should work also, double check all the teamcity builds id they all
have triggers set

**Comment by damianszczepanik** [comment]
At this stage I have one BB repo and one TC build and they work (trigger and build) together when plugin is configured by build. Should I configure something else at TC side so it works correctly by VCS?
I believe VCS ID is correct as I confirm what I see at config page with information provided by rest services and they are the same and this is what I've used for plugin configuration

**Comment by jmecosta** [comment]
Yes u need to setup trigger when change is pushed on tc side also

**Comment by damianszczepanik** [comment]
I have the trigger - same that works with build but it does not work for VCS or maybe the plugin does not trigger properly VCS. How can i debug it? What else should be configured for VCS?

**Comment by jmecosta** [comment]
U dont need trigger if u use build option. I can give a try to see if this
still works and let u know. Latee this week though.

To debug u can install atlas sdk and run the plugin in debug

**Comment by damianszczepanik** [comment]
Would be nice. I have no experience with debugging such plugins and also this is production installation so that might be hard to do.
If you can do that, please share BB configuration and TC as well so I can compare what I have lost.

**Comment by damianszczepanik** [comment]
I must say you were right when saying that triggering via VCS takes time. I thought that the trigger was not working while it needed up to hour to start the build which usually is not accepted time :(
Will try to decrease that time somehow.

**Comment by jmecosta** [comment]
So it works?

**Comment by damianszczepanik** [comment]
It does. And the performance is quite good (very similar to build type) when I try with new VCS connected with single build. So the delay problem is a TC issue
There is still some problem with TC which presents pending changes even they had been already built but this is not the plugin fault :)

**Comment by jmecosta** [comment]
Yeha, thats why we don't use it.. we never had really good results with it
