### ISSUE TITLE
plugin triggers "master" Branch Build, not the default branch in TeamCity

### ISSUE THREAD

**Issue by wemu** [TrimbleSolutionsCorporation/TeamcityTriggerHook#7]
Hallo

I've installed the plugin in out BitBucket 4.8 Server and can Trigger Builds in TeamCity 10 using the build config Id.

We have an issue with the branch names. The default branch name we use is refs/heads/master (which seems to be the default in bitbucket as well).
We have also enabled builds for pull requests by adding this into the branch specification of the VCS root in TeamCity:
`
+:refs/(pull-requests/*/from)
`

But the plugin triggers the build on "master" (not refs/heads/master) so the builds in TeamCity look weird (see screenshot):
![trigger-builds-branches](https://cloud.githubusercontent.com/assets/1943103/20838108/6a6be6d2-b8a7-11e6-8ce8-1857e6dba08a.png)

There are now detected changes on "refs/heads/master" and a build that ran (that was triggered) for "master".

Re-configuring the default branch to "master" somehow did not change this. Maybe that only works for new TeamCity builds.

Is it possible to specify the default branch name on the plugin?

Thanks!

**Comment by jmecosta** [comment]
@wemu thanks for reporting, you can overcome this if you use the followin in teamcity configuration (not in the default branch)

refs/heads/(master)

and default branch

refs/heads/master

then teamcity will only show "master" as default and you will be able to trigger from bitbucket

**Comment by wemu** [comment]
hello

Thanks for the feedback! I'm sorry I don't understand what goes where. The default branch for the VCS root has to be "refs/heads/master" and the "refs/heads/(master)" goes into the branch specification of the VCS root? Or are there checkout rules?

Thanks :)

**Comment by jmecosta** [comment]
No checkout rules, and that's the way I was saying.

Have you access to server logs? If you have can you put here.  should be
I'm Catalina with teamcity strings




On Thu, 8 Dec 2016, 17:50 Werner Mueller, <notifications@github.com> wrote:

hello

Thanks for the feedback! I'm sorry I don't understand what goes where. The
default branch for the VCS root has to be "refs/heads/master" and the
"refs/heads/(master)" goes into the branch specification of the VCS root?
Or are there checkout rules?

Thanks :)

—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/TrimbleSolutionsCorporation/TeamcityTriggerHook/issues/7#issuecomment-265773994>,
or mute the thread

**Comment by wemu** [comment]
I'm sorry I don't get where goes what.

- where should "refs/heads/(master)" go?
- and where should "refs/heads/master" go?

do you refer to the configuration in the BitBucket Server (The Hook) or is that within the TeamCity build? I'm not sure where your context of thinking is :)

Triggering builds works fine. Whats confusing is that a build is triggered for master and TeamCity still shows detected changes on "refs/heads/master" (as in the screenshot above)

Thanks!

**Comment by jmecosta** [comment]
OK I thought there were builds not trigger.  This is normal. If you want that to go way you can copy the configuration and rename ids

**Comment by jmecosta** [comment]
I think those usually go way after some time also

**Comment by wemu** [comment]
well yes the different branch builds go away (we usually keep the last 10 successful builds, after that the branches get cleaned out in that view). But I tried re-creating the build and have the exact same result: BitBucket triggers the build on "master" and TeamCity still detects changes on "refs/head/master". Although the default branch is set to "master". Weird thing.

We have some Parameters in TeamCity that configure the VCS Root. Do those confuse the association between the triggered build and the TeamCity detection?

**Comment by jmecosta** [comment]
ok, i ive replicated the problem. only now had the time to do it, sorry. i suppose the best is to add another place holder for "default branch" so you can trigger the default instead of master. suppose this behavior might have changed since the last time ive tried.

**Comment by wemu** [comment]
cool :)

that will probably do the trick. Do you think triggering builds from pull-requests will also work? Since those are on specific branches (+:refs/pull-requests/*/from resp. +:refs/pull-requests/*/merge). Or is that already possible using the custom branch regex?

**Comment by jmecosta** [comment]
i supose if you can get a regex that works with

```
        Pattern pattern = Pattern.compile(regx);
	Matcher matcher = pattern.matcher(data);                
        return matcher.matches();
```

should work

**Comment by jmecosta** [comment]
@wemu i have this now implemented, can you confirm that is works for your case? 

https://github.com/TrimbleSolutionsCorporation/TeamcityTriggerHook/releases/download/3.0.0/TeamcityTriggerHook-3.0.0-SNAPSHOT.jar

**Comment by jmecosta** [comment]
@wemu please reopen if its still a issue: its now in RC1 https://github.com/TrimbleSolutionsCorporation/TeamcityTriggerHook/releases/download/3.0.0-RC1/TeamcityTriggerHook-3.0.0-RC1.jar

**Comment by wemu** [comment]
@jmecosta hello, thanks for the notification! Im far away from my beloved teamcity this week - but I'll have a look next week. Thanks! :-)

**Comment by wemu** [comment]
@jmecosta I testesd the latest RC-8 on out TeamCity 10. Works perfectly :-)

Thanks a lot!

**Comment by jmecosta** [comment]
@wemu thanks, i will proceed wiht the release real soon
