### ISSUE TITLE
Builds in a PR

### ISSUE THREAD

**Issue by ifeldshteyn** [TrimbleSolutionsCorporation/TeamcityTriggerHook#79]
Hello,

We are on Bitbucket Server 7.17.2 and 4.10.1 plugin version.

We've noticed that builds triggered on a pull request don’t register in Stash under the pull request anymore, but under a commit hash now. 

In the screenshot below one of the commits references PR 717 - we can see the build in the list when looking under commits.

![image](https://user-images.githubusercontent.com/36711831/146055781-01cf207b-aa21-46cc-9c42-d12b6017642c.png)

However, when we look under that PR- the build list is empty.

www.mywebsite.com/repos/core/pull-requests/717/builds

![image](https://user-images.githubusercontent.com/36711831/146054055-9a17cae3-eb05-46ee-88b8-e62bda686088.png)

**Comment by jmecosta** [comment]
Hi

The hook itself doesn't really handle any build status information.

Those are usually send by teamcity side with commit status publisher.

So probably the best is to open a ticket to jetbrains since this is their
turf..

Regards
