### ISSUE TITLE
Passwords are fully visible in the audit log

### ISSUE THREAD

**Issue by tiny-cababge** [TrimbleSolutionsCorporation/TeamcityTriggerHook#8]
![image](https://cloud.githubusercontent.com/assets/11541572/23130836/d88b86e2-f77f-11e6-985b-bdceb6c4ee59.png)

**Comment by jmecosta** [comment]
Ups I will fix that. Thanks for reporting back

**Comment by jmecosta** [comment]
@tiny-cababge please try now with https://github.com/TrimbleSolutionsCorporation/TeamcityTriggerHook/releases/download/3.0.0/TeamcityTriggerHook-3.0.0-SNAPSHOT.jar

**Comment by tiny-cababge** [comment]
Wow! thanks for the super quick response. Testing it now thanks.

**Comment by tiny-cababge** [comment]
Couple of things
![image](https://cloud.githubusercontent.com/assets/11541572/23162794/95d28df2-f827-11e6-8422-3269f8971649.png)

1.  The changedevent audit still shows the pw. 
2.  The audit doesn't show any trigger kick off now, 
3.  This seem to have some new features (not that important but thought i'll mention it)
![image](https://cloud.githubusercontent.com/assets/11541572/23162877/06b0e8d4-f828-11e6-9174-56055705ee08.png) (Seems to have 2 field of the same)
4. I set this, hoping that a commit on any branch will kick of a build, but it didn't do anything for the newly created banch "develop" 
![image](https://cloud.githubusercontent.com/assets/11541572/23162924/3b486b80-f828-11e6-9669-c2e2d8a9e251.png)

**Comment by jmecosta** [comment]
ive uploaded a new version: https://github.com/TrimbleSolutionsCorporation/TeamcityTriggerHook/releases/download/3.0.0/TeamcityTriggerHook-3.0.0-SNAPSHOT.jar

1. the password would not be visible if you would run this in a new bitbukcet instance, however ive totally wipe the parameter from the soy template and in my instance the password is not longer there.

2. not sure what you mean, supose this is good :)
3. fixed
4. i supose it did not work because you have configured the trigger type to be vcs. In this case you need to use the vcs root id instead of buildconfiguration id. Ive swapped the order of the trigger so that by default it set to buildconfiguration. You will  need to save again the settings to make that permanent

let me know if this works now

**Comment by tiny-cababge** [comment]
Awesome, no password now. 
![image](https://cloud.githubusercontent.com/assets/11541572/23164225/0d6397b6-f82e-11e6-9311-271aa75d8b71.png)

4. Not starting for the develop branch
![image](https://cloud.githubusercontent.com/assets/11541572/23164284/42f6225e-f82e-11e6-9111-4bc7bc527be7.png)
![image](https://cloud.githubusercontent.com/assets/11541572/23164219/ff803eec-f82d-11e6-9ba8-2d3c864406b4.png)
This is my complete setting, and I can't seem to get it to kick off when a checkin is made to the develop branch.

**Comment by tiny-cababge** [comment]
![image](https://cloud.githubusercontent.com/assets/11541572/23164380/a82fc698-f82e-11e6-88cf-8894e4a57be8.png)
Pic of teamcity detecting the changes.

**Comment by jmecosta** [comment]
alright, your regx is incorrect. you should use `` .*``

but anyway, it would have a crash with your branch name also. ive updated a fix for that. its a bit tricky to get the logical names right for everyone. in your case this will work

refs/heads/(develop) -> develop

however this might be failing if
refs/heads/(ex/develop) -> ex/develop <- this for now will fail. i need to think of a better way handling those. perhaps best to let user define the logical branchs to trigger.

if still fails check the bitbucket logs, there should be exceptions explaining what is happening:

``
[INFO] [talledLocalContainer] [TeamcityTriggerHook] 20170221_142011 Trigger builds for branch: develop
[INFO] [talledLocalContainer] [TeamcityTriggerHook] Trigger BuildId: sdfsds
[INFO] [talledLocalContainer] 2017-02-21 14:20:11,556 WARN  [AtlassianEvent::thread-1] admin @LD0ZBAx860x894x0 10.42.76.176 "POST /scm/project_1/rep_1.git/git-receive-pack HTTP/1.1" BitbucketTeamcityHook Hook Request: http://teamcity/app/rest/buildQueue
[INFO] [talledLocalContainer] java.io.FileNotFoundException: http://teamcity/app/rest/buildQueue
``

**Comment by jmecosta** [comment]
@tiny-cababge and looking at your vcs definition. refs/heads/pull-request/(*/develop) will not trigger anything in teamcity side, since those are not seen in the async hook that runs after each commit. im triying to support pr trigger in here: https://github.com/TrimbleSolutionsCorporation/TeamcityTriggerHook/issues/9 

but for those they cannot be comming from the regx side but only for the feature/hotfix/bugfix types that are expect to generate pull requests

**Comment by tiny-cababge** [comment]
I triewd changing my teamcity branch spec to *
![image](https://cloud.githubusercontent.com/assets/11541572/23167432/31b6e8da-f83c-11e6-8a3e-e401dd8ff0cd.png)

and in the plugin to this:
![image](https://cloud.githubusercontent.com/assets/11541572/23167401/1b30b2ee-f83c-11e6-9b20-211a9d1d8f7a.png)

but still no luck, i also tried finding the logs but i can't see any entries. Can you share a screenshot of your configs please, where you've got it to detect the develop branch.

**Comment by jmecosta** [comment]
![image](https://cloud.githubusercontent.com/assets/1041352/23167743/4d3b7bd6-f84e-11e6-8bbe-eab4ea5c2d25.png)

and then on log i get this:

![image](https://cloud.githubusercontent.com/assets/1041352/23167795/6a8ad790-f84e-11e6-9e38-2dcac851ba0d.png)

if you are not having any entry in log, then there must be something incorrect and i dont expect to be sent to teamcity. 

this is the main config. so nothing out of the ordinary
![image](https://cloud.githubusercontent.com/assets/1041352/23167863/bc11422a-f84e-11e6-8a76-d2d34d666751.png)

i havent done any config in teamcity side, but i expect in the vcs root config this to work

default: refs/heads/master

defs:
refs/heads/(develop) -> you really need to set the () here because the hook will trigger branch develop and not refs/heads/develop

**Comment by tiny-cababge** [comment]
Thanks for the help so far, but I just really can't seem to get the develop branch building, no matter what combination I try. 
![image](https://cloud.githubusercontent.com/assets/11541572/23169076/4fe8886c-f842-11e6-99e9-9ac091ea44ba.png)

![image](https://cloud.githubusercontent.com/assets/11541572/23169083/55e85cf6-f842-11e6-8e14-be023343c6bb.png)

![image](https://cloud.githubusercontent.com/assets/11541572/23169247/ec280996-f842-11e6-8bd7-ee5923036fa1.png)

**Comment by tiny-cababge** [comment]
However the master branch works fine, 

![image](https://cloud.githubusercontent.com/assets/11541572/23169393/847f3e9e-f843-11e6-8d50-f8d4af7f6c05.png)

I did however notice there's 2 type of master, a default master and a ref/heads/master

**Comment by jmecosta** [comment]
As far as I see you have everything correctly set, the only thing you need
to see is bitbucket log. As the master is running then we should see some
logging for the develop branch also.can you dig those ones from the log?

The several master definition might be because you are changing the vcs
definition in same config

**Comment by tiny-cababge** [comment]
The only log i can see is atlassianbitbucket-stdout.2017-02-21

[TeamcityTriggerHook] 20170221_105252 Trigger builds for branch: master
[TeamcityTriggerHook] Trigger BuildId: Playground_StashTeamcitypushtest

when i run it for the develop branch. i see no updates in that log or this atlassianbitbucket-stderr.2017-02-21

**Comment by jmecosta** [comment]
OK then it's the reason it does not trigger. Can you send me all your
configurations. I try to replicate here.  See if if I can find were the
fault his.

I might also add a develop option. Similar to master since it's very common
to find develop branch on top of master

**Comment by jmecosta** [comment]
And do a git ls-remote so can I check what are the name of the branches in
server

**Comment by tiny-cababge** [comment]
This is out teamcity config. 

<?xml version="1.0" encoding="UTF-8"?>
<build-type xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" uuid="104d902a-17a3-4ed5-9516-77f182b1e1a0" xsi:noNamespaceSchemaLocation="http://www.jetbrains.com/teamcity/schemas/10.0/project-config.xsd">
  <name>StashTeamcitypushtest</name>
  <description>Test update to see if it gets reflected in stash</description>
  <settings>
    <options>
      <option name="allowExternalStatus" value="true" />
      <option name="buildNumberPattern" value="%build.majorVersion%.%build.minorVersion%.%build.patchVersion% (?)" />
      <option name="checkoutMode" value="ON_AGENT" />
      <option name="cleanBuild" value="true" />
      <option name="shouldFailBuildOnAnyErrorMessage" value="true" />
      <option name="showDependenciesChanges" value="true" />
    </options>
    <disabled-settings>
      <setting-ref ref="RUNNER_520" />
    </disabled-settings>
    <parameters>
      <param name="build.commitHash" value="" spec="text description='Optional, defaults to %build.vcs.number%' validationMode='any' display='hidden'" />
      <param name="build.currentBranch" value="" spec="text description='Defaults to the name of the current branch' validationMode='any' display='hidden'" />
      <param name="build.informationalVersion" value="" spec="text description='Optional, defaults to %build.semanticVersion% %build.branchName%@%shortCommitHash%' validationMode='any' display='hidden'" />
      <param name="build.majorVersion" value="1" spec="text description='Will be used as part of the build number: Major.Minor.Patch' validationMode='not_empty' label='Major version' display='prompt'" />
      <param name="build.minorVersion" value="0" spec="text description='Will be used as part of the build number: Major.Minor.Patch' validationMode='not_empty' label='Minor version' display='prompt'" />
      <param name="build.nugetVersionForDebug" value="" spec="text description='Optional, defaults to %build.semanticVersion%-d-%build.semanticVersionSpecial% with special version truncated to 18 characters' validationMode='any' display='hidden'" />
      <param name="build.nugetVersionForRelease" value="" spec="text description='Optional, defaults to %build.semanticVersion%-r-%build.semanticVersionSpecial% with special version truncated to 18 characters' validationMode='any' display='hidden'" />
      <param name="build.patchVersion" value="%build.counter%" spec="text description='Optional, will be used as part of the build number: Major.Minor.Patch. Defaults to %build.counter%' validationMode='any' label='Patch version' display='normal'" />
      <param name="build.releaseBranch" value="master" spec="text validationMode='any' display='hidden'" />
      <param name="build.semanticVersion" value="" spec="text description='Optional, defaults to %build.majorVersion%.%build.minorVersion%.%build.patchVersion%' validationMode='any' display='hidden'" />
      <param name="build.semanticVersionFull" value="" spec="text description='Optional, defaults to %build.semanticVersion%-%build.semanticVersionSpecial%' validationMode='any' display='hidden'" />
      <param name="build.semanticVersionSpecial" value="" spec="text description='Optional, will be used as part of the Semantic version: Major.Minor.Patch-Special. Defaults to %build.currentBranch% truncated to 18 characters' validationMode='any' label='Special version' display='normal'" />
      <param name="build.shortCommitHash" value="" spec="text description='Optional, defaults to %build.vcs.number%.Substring(0, 7)' validationMode='any' display='hidden'" />
      <param name="build.version" value="" spec="text description='Optional, defaults to %build.majorVersion%.%build.minorVersion%.%build.patchVersion%.0' validationMode='any' display='hidden'" />
      <param name="system.company.developers_team.nexus.publishUrl" value="http://nexus.company.com/nexus/service/local/nuget/nuget-company-hosted/" />
      <param name="system.company.developers_team.nuget.publishUrl" value="https://nuget.company.com" spec="text description='URL to publish NuGet packages to our NuGet feed' validationMode='not_empty' label='NuGet Publish URL' display='hidden'" />
      <param name="system.company.developers_team.octopus.publishUrl" value="https://octopusdeploy.company.com/nuget/packages" spec="text description='URL to publish NuGet packages to Octopus Deploy' validationMode='not_empty' label='Octopus Publish URL' display='hidden'" />
      <param name="system.company.developers_team.stash.branchSpecification" value="*" spec="text validationMode='not_empty' display='hidden'" />
      <param name="system.company.developers_team.stash.defaultBranchName" value="master" />
      <param name="system.company.developers_team.stash.repositoryName" value="test2" />
      <param name="system.nexus_api_key" value="zxxcbb86d2415b749af34afdsfdsfdsfdsfdsf20dsdsdsds8a782657dd20f82f73aea9924d623988bc0" spec="password display='hidden' label='system.nexus_api_key'" />
    </parameters>
    <build-runners>
      <runner id="RUNNER_356" name="" type="MR_TC_InitializeBuildCommonParams">
        <parameters>
          <param name="mr.initialize_build.releaseBranch" value="%build.releaseBranch%" />
          <param name="mr.initialize_build.verbose" value="SilentlyContinue" />
          <param name="teamcity.step.mode" value="default" />
        </parameters>
      </runner>
      <runner id="RUNNER_128" name="" type="simpleRunner">
        <parameters>
          <param name="script.content" value="dir" />
          <param name="teamcity.step.mode" value="default" />
          <param name="use.custom.script" value="true" />
        </parameters>
      </runner>
      <runner id="RUNNER_520" name="DIR2" type="simpleRunner">
        <parameters>
          <param name="script.content"><![CDATA[dir
ipconfig]]></param>
          <param name="teamcity.step.mode" value="default" />
          <param name="use.custom.script" value="true" />
        </parameters>
      </runner>
    </build-runners>
    <vcs-settings>
      <vcs-entry-ref root-id="DevelopersTeamStash" />
    </vcs-settings>
    <requirements />
    <build-triggers />
    <build-extensions>
      <extension id="BUILD_EXT_18" type="teamcity.stash.status">
        <parameters>
          <param name="secure:stash_username" value="zxx97a54ad85c6e9188177f8cd0b5021d1a" />
          <param name="stash_failCancelledBuilds" value="true" />
          <param name="stash_host" value="https://stash.company.com" />
          <param name="stash_only_latest" value="true" />
          <param name="stash_username" value="svcBuild" />
        </parameters>
      </extension>
      <extension id="BUILD_EXT_81" type="VcsLabeling">
        <parameters>
          <param name="branchFilter" value="+:master" />
          <param name="labelingPattern" value="v%build.semanticVersion%" />
          <param name="successfulOnly" value="true" />
          <param name="vcsRootId" value="DevelopersTeamStash" />
        </parameters>
      </extension>
    </build-extensions>
    <cleanup />
  </settings>
</build-type>

**Comment by tiny-cababge** [comment]
git ls remote 
![image](https://cloud.githubusercontent.com/assets/11541572/23171543/a695ad9a-f84a-11e6-8662-86cecdadbf47.png)

**Comment by jmecosta** [comment]
@tiny-cababge i cant replicate your behaviour.  in my environment it works using the same configuration as you.

ive uploaded a new version that hads more logging.

should be like this
![image](https://cloud.githubusercontent.com/assets/1041352/23173393/b0e7980a-f861-11e6-9472-61e4ca7d4e4f.png)

try and let me know

**Comment by tiny-cababge** [comment]
where is the new version? 

This one is from 18hours ago. 
https://github.com/TrimbleSolutionsCorporation/TeamcityTriggerHook/releases/download/3.0.0/TeamcityTriggerHook-3.0.0-SNAPSHOT.jar

**Comment by jmecosta** [comment]
its that one, 19 hours is when release is done. ive been deleting and updating a new version everytime

**Comment by tiny-cababge** [comment]
I'm going to close this ticket as the "not building develop branch" is another issue and the original problem of password showing is fixed. 

I've downloaded the code and the atlassian sdk, i'm going to see if i can figure out why its not working for me. 

thanks for all the help @jmecosta

**Comment by tiny-cababge** [comment]
Oh, just tried the new version with the extra logging, everything seems to be working.... weird? 

![image](https://cloud.githubusercontent.com/assets/11541572/23206035/146a0bd8-f8e4-11e6-89bf-2b7622c26245.png)

**Comment by jmecosta** [comment]
Nop, I think you have been using the one that was broken.  I've made the
fix for it in one of the first updates. So I supose it was all along you
were using a incorrect version.

Anyway great that it works for you

**Comment by jmecosta** [comment]
@tiny-cababge feel free to give feedback on the manual trigger
