### ISSUE TITLE
Bitbucket 8.x support

### ISSUE THREAD

**Issue by mieliespoor** [TrimbleSolutionsCorporation/TeamcityTriggerHook#85]
What does the support look like for Bitbucket 8.x?

Any idea when support will be available?

**Comment by jmecosta** [comment]
can u install the current version there, and see if it works?

then its just a matter of adjusting the max version in the release page

**Comment by mieliespoor** [comment]
It's not so easy. If we upgrade and updates are required, we will leave a number of teams out in the cold. We can't be risking that in a corporate environment. Hence we asked here.

**Comment by jmecosta** [comment]
Ok. Then u need to wait a bit. I let u know when it's done.

**Comment by ivan1767p** [comment]
> What does the support look like for Bitbucket 8.x?

Worked well on:
TeamCity Professional 2020.2.4 (build 86063)
Atlassian Bitbucket v7.6.3

I can't say anything about Bitbucket 8.x

**Comment by ivan1767p** [comment]
@mieliespoor I did not see any cardinal differences between 7 and 8 Bitbucket versions. Try this in a "staged/test" install of your environment. Don't try on the production environment.

**Comment by mieliespoor** [comment]
I forgot about this. We upgraded at some point and currently running v8.8.2. We haven't seen any issues.

**Comment by jmecosta** [comment]
Actually I've notice the test connection buttons don't work in 8.x

Have u confirm this is working?
